apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-akb0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-akb0
    app.kubernetes.io/part-of: test-app-axhn
  name: devfile-sample-python-basic-akb0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-akb0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-akb0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-vroc-tenant/test-app-axhn/devfile-sample-python-basic-akb0@sha256:d9c15d8db75384e5a14d0f3ab9d4f4430350eb171a2f0bb3f770cdf1f00fe583
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
